Create metadata parsing strategy
devoxa/paddle-sdk pull request #88
Opened 2020-12-14 21:23 UTC by aradzie

2020-12-14 21:25 UTC, aradzie commented
I wanted to create a draft pull request but clicked the wrong button. Please don't merge yet.

2020-12-15 19:27 UTC, aradzie commented
I think this PR is in a good shape, PTAL.

2020-12-18 21:24 UTC, queicherius requested changes
Looks very good, some small changes to align to my codestyle as already discussed :)

2020-12-18 21:24 UTC, queicherius commented on README.md
It would be great to add a small section about which codes are available to the docs. Just their names, and the short comment you already wrote in `metadata.ts`.

2020-12-18 21:24 UTC, queicherius commented on src/index.ts
> +  readonly metadataCodec: MetadataCodec<TMetadata>
Tiny nitpick - add newlines

```suggestion
export interface PaddleSdkOptions<TMetadata = unknown> {
  /** Public key from the paddle dashboard to validate webhook requests */
  readonly publicKey: string

  /** Vendor ID from the paddle dashboard to authenticate API requests */
  readonly vendorId: number

  /** Vendor auth code from the paddle dashboard to authenticate API requests */
  readonly vendorAuthCode: string

  /**
   * Metadata codec encodes and decodes additional pass-through data for an order
   *
   * @see https://developer.paddle.com/guides/how-tos/checkout/pass-parameters
   */
  readonly metadataCodec: MetadataCodec<TMetadata>
```

2020-12-18 21:24 UTC, queicherius commented on src/index.ts
> +  constructor({ publicKey, vendorId, vendorAuthCode, metadataCodec }: PaddleSdkOptions<TMetadata>) {
Avoid parameter destructoring for option objects like this, because it makes it less clear where the variable came from 

```ts
// I have to scroll up to see what metadataCodec is
this.metadataCodec = metadataCodec

// I know that it's the unmodified options that were passed to this class
this.metadataCodec = options.metadataCodec
```

2020-12-18 21:24 UTC, queicherius commented on src/index.ts
> +      throw new PaddleSdkException('PaddleSdk was called with an invalid metadata codec')
For consistency with the other messages

```suggestion
      throw new PaddleSdkException('PaddleSdk was called without a metadataCodec')
```

2020-12-18 21:24 UTC, queicherius commented on src/metadata.ts
> +  readonly parse: (passthrough: string) => TMetadata
```suggestion
  /** Stringifies the given metadata value to a `passthrough` string */
  readonly stringify: (metadata: TMetadata) => string

  /** Parses the given `passthrough` string to a metadata value */
  readonly parse: (passthrough: string) => TMetadata
```

2020-12-18 21:24 UTC, queicherius commented on src/metadata.ts
> + */
```suggestion
/** Creates a new metadata codec which passes through metadata strings unmodified */
```

2020-12-18 21:24 UTC, queicherius commented on src/metadata.ts
> + */
```suggestion
/** Creates a new metadata codec which uses `JSON` to stringify and parse metadata values */
```

2020-12-18 21:24 UTC, queicherius commented on src/metadata.ts
> + * @param encryptionKey The encryption key which is used to encrypt/decrypt the `passthrough` strings
I generally avoid `@param` jsdoc because it does not add any real value IMO.

2020-12-24 13:13 UTC, aradzie commented
I have fixed all the comments. Please review the new documentation section about the metadata codecs.

PS My apologies for the late reply. One week I drug myself with code to give myself productivity boost. The next week I cannot drag myself to the computer to do anything useful.

2020-12-26 13:05 UTC, queicherius commented
Just a small note for next time - please don't force-push into PRs once the initial review is done.

The reason for that is that it makes it impossible to just look at the diff between the initial review and "now" to see if all review-points are checked. Instead the reviewer has to check all files that changed again fully.

2020-12-26 13:11 UTC, queicherius approved these changes
Awesome, thank you for the changes! 👍

2020-12-26 13:11 UTC, merged