Payment events
devoxa/paddle-sdk pull request #92
Opened 2020-12-15 10:10 UTC by aradzie

2020-12-15 19:25 UTC, aradzie commented
I tested this PR by deploying a sample application which uses the new code and then using WebHook simulator from the Paddle dashboard.

2020-12-18 22:52 UTC, queicherius requested changes
One tiny change, the rest looks awesome 👍

2020-12-18 22:52 UTC, queicherius commented on src/index.ts
> +      productId: body.product_id,
Parse as an integer, for consistency with subscription hooks
```suggestion
      productId: convertApiInteger(body.product_id),
```

2020-12-26 13:14 UTC, queicherius approved these changes
💯 Perfect

2020-12-26 13:19 UTC, merged